homeassistant:
  # Name of the location where Home Assistant is running
  name: Hermes Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude 
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Vilnius
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

#recorder:
  #db_url: !secret hass_sql 


# Enables configuration UI
automation: !include automations.yaml
config:

#mqtt:
#  broker: core-mosquitto
#  port: 1883
#  client_id: hassio
#  username: !secret mqtt_username
#  password: !secret mqtt_password
#
http:
  # Uncomment this to add a password (recommended!)
#  api_password: !secret hass_api_password
#  base_url: !secret hass_url
#  ssl_certificate: /ssl/fullchain.pem
#  ssl_key: /ssl/privkey.pem


# Checks for available updates
updater:

# Discover some devices automatically
discovery:

#device_tracker:
#  - platform: nmap_tracker
#    hosts: 192.168.0.1/24
#    home_interval: 10
#    exclude:
#     - 192.168.0.107
#     - 192.168.0.1
#     - 192.168.0.2
#     - 192.168.0.3
#     - 192.168.0.4
#     - 192.168.0.103

#ios:
# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
#sun:


# tts:
#   platform: google

#sensor: !include sensors.yaml
#scene: !include scenes.yaml
#input_boolean: !include input_booleans.yaml
#script: !include scripts.yaml
switch: !include switches.yaml
#group: !include groups.yaml
light: !include lights.yaml

media_player: !include media_players.yaml


#logger:
#  default: warning
#  logs:
#    homeassistant.components.switch.hdmi: debug


#
#panel_iframe:
#  router:
#    title: 'Socket'
#    url: 'http://192.168.0.4'


# HYPERION

input_select:
  hyperion_effects:
    name: Hyperion Effects
    options: !include hyperion_effect_list.yaml
    initial: Rainbow swirl
    icon: mdi:white-balance-iridescent

shell_command:
  run_hyperion_effect:  "ssh -i /config/.ssh/id_rsa pi@192.168.1.123 \"hyperion-remote -e '{{states.input_select.hyperion_effects.state}}'\" "
