- platform: command_line
  switches:
    hyperion_service:
      command_on: "ssh -i /config/ssh/id_rsa  pi@192.168.1.123 'sudo systemctl start hyperion.service'"
      command_off: "ssh -i /config/ssh/id_rsa pi@192.168.1.123 'sudo systemctl stop hyperion.service'"
      friendly_name: Hyperion Service

- platform: command_line
  switches:
    test_ssh:
      command_on: "ssh -i /config/ssh/id_rsa pi@192.168.1.123 'echo hass-did-it >> /home/homeassistant/test-ssh.txt'"
      friendly_name: Magic Test Switch
